apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-deployment-1
spec:
  selector:
    matchLabels:
      app: simple-nodejs-pod
  template:
    metadata:
      labels:
        app: simple-nodejs-pod
    spec:
      containers:
      - name: simple-nodejs-container
        image: faawidia/simple-nodejs-microservice:latest
        env:
          - name: APP_PORT
            value: "3000"
          - name: SVC_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-service
spec:
  type: NodePort
  selector:
    app: simple-nodejs-pod
  ports:
  - port: 3000
    targetPort: 3000

